apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: parse-server-namespace
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
      containers:
        - name: mongo-db
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: "mongo-server"
          volumeMounts:
            - mountPath: "/data/mongodb"
              name: mongo-persistent-storage
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1024m"   
