apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: parse-server-namespace
  name: mongodb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
