apiVersion: v1
kind: Service
metadata:
  namespace: parse-server-namespace
  name: parse-server-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 1337
  selector:
    app: parse-server
